name: Teste de Carga

on:
  workflow_call:

jobs:
  
  loadtest:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v5
    
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v5.0.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2 
